CYBRSOURCE-55
vtex-apps/cybersource pull request #106
Opened 2022-10-26 18:50 UTC by btalma

Ecuador payload customizations: add shipping tax as a line item in the format:
{
    "productName": "ADMINISTRACION MANEJO DE PRODUCTO", //same name always
    "productSKU": "", //not required by CS, can be omitted (preferable) or empty
    "quantity": "1", //always 1
    "unitPrice": "25.00", // Shipping cost without taxes
    "taxAmount": "25.00", // unitPrice * quantity
     "taxDetails": [
      {
        "type": "national",
        "amount": "3.00"  // taxAmount * taxRate (based on configuration in the account)
      }
    ]
  }

2022-11-08 17:29 UTC, AnnaChiu95 reviewed
Is `taxAmount` the taxable value? 

How do we test these changes?

2022-11-08 18:32 UTC, btalma commented
"taxAmount": should be unitPrice * quantity
The change can be tested on sandboxusdev by making sure that the Region is set to Ecuador on the Cybersource admin page and checking out.  The payload can be viewed in OpenSource.
https://developer.logs.vtex.com/_dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2h,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'2cab9aa0-5c56-11ed-862d-710ea72622fc',key:Attributes.app,negate:!f,params:(query:'vtex.cybersource*'),type:phrase),query:(match_phrase:(Attributes.app:'vtex.cybersource*'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'2cab9aa0-5c56-11ed-862d-710ea72622fc',key:Attributes.workflow_type,negate:!f,params:(query:CreatePayment),type:phrase),query:(match_phrase:(Attributes.workflow_type:CreatePayment))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'2cab9aa0-5c56-11ed-862d-710ea72622fc',key:Attributes.account,negate:!f,params:(query:sandboxusdev),type:phrase),query:(match_phrase:(Attributes.account:sandboxusdev)))),index:'2cab9aa0-5c56-11ed-862d-710ea72622fc',interval:auto,query:(language:kuery,query:''),sort:!())

2022-11-08 19:57 UTC, polishq requested changes

2022-11-08 19:57 UTC, polishq commented on dotnet/Services/CybersourcePaymentService.cs
> +                                        shippingTax += (long)Math.Round(vtexOrderItem.SellingPrice * priceTag.RawValue, MidpointRounding.AwayFromZero);
`vtexOrderItem.SellingPrice` is incorrect ... the tax rate needs to be applied to the shipping cost, not the item cost. Maybe you can just store the shipping tax rate here, and then use it to calculate the tax when you build the shipping tax line item?

2022-11-10 18:10 UTC, polishq approved these changes
LGTM

2022-11-10 18:10 UTC, merged